### ISSUE TITLE
Tribler missing dependencies and M2Crypto error on fc24

### ISSUE THREAD

**Issue by jalbstmeijer** [UnitedRPMs/tribler#1]
Description of problem:

Tribler won't start.

```
ImportError: No module named chardet
ImportError: No module named feedparser
```

after installing `python-chardet`python-feedparser` we get an M2Crypto error.

Version-Release number of selected component (if applicable):

```
tribler-6.6.0-0.exp1.2.fc24
```

How reproducible:

Steps to Reproduce:
1. Install tribler
2. try to start tribler
3. install missing dependencies
4. try to start tribler

Actual results:

first

```
ImportError: No module named chardet
```

and

```
ImportError: No module named feedparser
```

after installing these missing dependencies we get;

``` python
$ tribler
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 989, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 115, in __init__
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 342, in InitStage1
    session = Session(self.sconfig, autoload_discovery=autoload_discovery)
  File "/usr/lib/python2.7/site-packages/Tribler/Core/Session.py", line 124, in __init__
    self.keypair = permidmod.generate_keypair()
  File "/usr/lib/python2.7/site-packages/Tribler/Core/permid.py", line 25, in generate_keypair
    ec_keypair = EC.gen_params(KEYPAIR_ECC_CURVE)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 269, in gen_params
    return EC(m2.ec_key_new_by_curve_name(curve), 1)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 106, in __init__
    assert m2.ec_key_type_check(ec), "'ec' type error"
ValueError: Received a NULL pointer.
```

Expected results:

running application

Additional info:

https://github.com/Tribler/tribler/issues/893
https://github.com/Tribler/tribler/issues/719
https://github.com/Tribler/tribler/issues/1841

**Comment by paulcarroty** [comment]
@sergiomb2

**Comment by sergiomb2** [comment]
```
assert m2.ec_key_type_check(ec), "'ec' type error"
ValueError: Received a NULL pointer.
```

means that you don't ec (ecliptic curve) you need install  openssl unhobble , is work in progress . 
https://github.com/sergiomb2/openssl

packages here: https://github.com/UnitedRPMs/openssl/releases/tag/1.0.2j-2
@paulcarroty   can you publish ? please , Thanks.
