### ISSUE TITLE
schema_sdb_v28.sql not where it is expected

### ISSUE THREAD

**Issue by jalbstmeijer** [UnitedRPMs/tribler#3]
rpm provides /usr/lib/python2.7/site-packages/Tribler/schema_sdb_v28.sql

$ tribler
ERROR   1477171150.13            util:239   Exception raised on the reactor's thread 'SQL script doesn't exist: /usr/share/tribler/Tribler/schema_sdb_v28.sql'.
 Traceback from this thread:
  File "/usr/bin/tribler", line 95, in <module>
    **main**()
  File "/usr/bin/tribler", line 85, in **main**
    run()
  File "/usr/bin/tribler", line 68, in run
    run_main()
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 989, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 115, in **init**
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 344, in InitStage1
    self.upgrader = session.prestart()
  File "/usr/lib/python2.7/site-packages/Tribler/Core/Session.py", line 183, in prestart
    self.sqlite_db.initialize()
  File "/usr/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, _args, *_kargs)
  File "/usr/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 236, in blockingCallFromThread
    this_thread_tb = traceback.extract_stack()

 Traceback from the reactor's thread:
   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/Tribler/Core/CacheDB/sqlitecachedb.py", line 87, in initialize
    self._open_connection()
  File "/usr/lib/python2.7/site-packages/Tribler/Core/CacheDB/sqlitecachedb.py", line 163, in _open_connection
    raise OSError(msg)

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 989, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 115, in **init**
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/usr/lib/python2.7/site-packages/Tribler/Main/tribler_main.py", line 344, in InitStage1
    self.upgrader = session.prestart()
  File "/usr/lib/python2.7/site-packages/Tribler/Core/Session.py", line 183, in prestart
    self.sqlite_db.initialize()
  File "/usr/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, _args, *_kargs)
  File "/usr/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 240, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
OSError: SQL script doesn't exist: /usr/share/tribler/Tribler/schema_sdb_v28.sql

**Comment by kuboosoft** [comment]
Solved in new version ;)
